### ISSUE TITLE
Allow using buffers instead of files

### ISSUE THREAD

**Issue by fbeutel** [remram44/rs-sync#8]
It would be nice if the public API of this crate would allow to call apply_diff and hash_files (or equivalent functions) with buffers that implement the Read, Seek and Write trait (as needed).

It seems like this is already the case for delta::write_delta_file_single.

This would allow for cases where one of the participating files is not accessible by the local file system.

**Comment by remram44** [comment]
For hashing, you can already use `Hashes::hash()` to index a new file. You need to provide some kind of name (as a `PathBuf`) associated with it, but that doesn't need to be a local file name.

Doing this for `apply_diff()` is difficult, because the function needs to get random blocks from random files (the source file + the reference files) to reconstruct the target. Maybe it could accept a map of (`path`, `Read+Seek`) entries instead of filenames? It would also be more efficient to keep the files open rather than opening them when a block is needed (they all get opened by `hash_files()` right away).

**Comment by remram44** [comment]
82b87c03 & 346328f0 add `apply_diff_map()` which takes such a map and read blocks from that.

**Comment by remram44** [comment]
Irrelevant after complete redesign.
